[package]
name = "tt-dns"
version = "0.2.0"
authors = ["The TT Team"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3", default-features = false }
rand = "*"
